name: Build dependencies & push to artifactory

on:
  push:
  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-13]
        include:
          - os: ubuntu-22.04
            profile: profile_linux
          - os: windows-2022
            profile: profile_win
          - os: macos-13
            profile: profile_mac
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install Conan
        run: pip install -r requirements.txt
      - name: Configure Conan remotes
        shell: bash
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
        run: |
          conan remote disable conancenter
          conan remote add swift https://artifactory.swift-project.org/artifactory/api/conan/conan-local
          conan remote login swift "$ARTIFACTORY_USER" --password "$ARTIFACTORY_TOKEN"
      - name: Build libraries
        shell: bash
        run: |
          conan profile detect
          conan install . -pr=${{ matrix.profile }} --build=missing
      - name: Upload libraries
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: |
          conan upload "*" -r swift --confirm
